name: Output Information on Github Events
on: workflow_dispatch
jobs:
  informationjob:
    runs-on: ubuntu-latest
    steps:
      - name: Output Github Context
        run: echo "${{ toJSON(github.events)}}"